name: Lint

on:
  push:
    branches:
      - main
      - master
      - 3.2.0_downgraded_deps
  pull_request:
    branches:
      - main
      - master
      - 3.2.0_downgraded_deps
  schedule:
    - cron: '28 20 2 * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo fmt --all -- --check

      - name: Install OpenCL
        run: sudo apt-get install nvidia-opencl-dev

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets
