name: Test

on:
  push:
    branches:
      - main
      - master
      - 3.2.0_downgraded_deps
    pull_request:
    branches:
      - main
      - master
      - 3.2.0_downgraded_deps

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Install OpenCL
        run: sudo apt-get install nvidia-opencl-dev
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
